### ISSUE TITLE
ClamAV Thread Header always "no"

### ISSUE THREAD

**Issue by ripkens** [postalserver/postal#406] opened 2017-11-17 13:02 UTC
To have the X-Postal-Threat header set to be true if ClamAV finds a Threat, one Line has to be changed in **/app/jobs/unqueue_message_job.rb Line 132**

Old: `"X-Postal-Threat: #{queued_message.message.threat == 1 ? 'yes' : 'no'}"`
New: `"X-Postal-Threat: #{queued_message.message.threat ? 'yes' : 'no'}"`

**The Problem is, that the mail inspection returns "true" or "false" not 1 or 0**

Additionaly, an extra header should be added:

`"X-Virus-Status: #{queued_message.message.threat_details}"`

**Comment by ripkens** [comment] 2017-11-17 13:04
Additionally, a global setting should be introduced how to handle Virus checks (Mark, HardFail, Scores etc.).

**Comment by willpower232** [comment] 2017-11-18 21:38
Soudns good, are you able to make a pull request for this?

**Comment by ripkens** [comment] 2017-11-18 21:43
Done ...

**Comment by willpower232** [comment] 2017-11-18 21:44
Lovely, hopefully atech will get round to some merges soon...

**Comment by willpower232** [comment] 2018-01-14 14:26
@ripkens your commit never left your fork, can you make a pull request to this repository?

**Comment by ripkens** [comment] 2018-01-14 23:47
The pull request is here:https://github.com/atech/postal/pull/408

**Comment by willpower232** [comment] 2018-01-15 09:13
Ah my mistake sorry

**Comment by tankerkiller125** [comment] 2018-05-07 21:55
I added the code from this request into my own deployment for testing, running http://www.emailsecuritycheck.net on my server for receiving postal never detected any of the test files as a Virus even though it should have?

**Comment by adamcooke** [comment] 2021-07-30 22:11
Duplicate of #206

**Closed by adamcooke** 2021-07-30 22:11 UTC
Labels: bug
