### ISSUE TITLE
Postal server cannot send webhook API calls 

### ISSUE THREAD

**Issue by belghitioth** [postalserver/postal#2398] opened 2023-04-03 10:01 UTC
## Describe the bug

Postal server cannot send webhook API calls. 

## To Reproduce

1. Configure a Webhook endpoint

![Screenshot from 2023-04-03 11-55-38](https://user-images.githubusercontent.com/17969052/229476544-a56d8aaf-3a36-4768-8231-6e4deb226086.png)

2. Send an email through the UI or using SMTP Protocol

![Screenshot from 2023-04-03 11-57-13](https://user-images.githubusercontent.com/17969052/229476906-3b45d7cd-0011-4f66-ba9e-e204ff9fc980.png)

3. Check Outgoing Messages Tab from Messages page 

![Screenshot from 2023-04-03 11-54-25](https://user-images.githubusercontent.com/17969052/229476301-edad3433-ca5a-4d2b-bfc1-d0af6e2c7b78.png)

4. There is an error after sending the email related to the webhook

![Screenshot from 2023-03-30 11-00-45](https://user-images.githubusercontent.com/17969052/229476747-9dd59a43-782d-40f6-817d-40ed987fa5dc.png)

5. The webhook API call is not sent

## Expected behaviour

Postal server is sending an API call to the endpoint configured in Postal UI with success.

## Screenshots

![Screenshot from 2023-03-30 11-00-45](https://user-images.githubusercontent.com/17969052/229477836-08cd79bb-825d-4ebc-bfd9-4e58b39d9e6b.png)

## Environment details 

 - OS: Ubuntu 
 - Browser : Chrome
 - Version : 110 
 - Type : Desktop

## Additional information/context

I checked the logs of postal-worker container and it seems to be related to the line 41 on `app/models/webhook_request.rb `when the payload is being serialized by Hash:

`server.webhook_requests.create!(:event => event, :payload => payload, :webhook => webhook, :url => webhook.url)
`

I found this fix : https://stackoverflow.com/questions/72970170/upgrading-to-rails-6-1-6-1-causes-psychdisallowedclass-tried-to-load-unspecif

It seems to be related to the latest version of Postal.

**Comment by willpower232** [comment] 2023-04-03 11:03
see also #2397

**Comment by catphish** [comment] 2023-04-11 19:41
I've just tested and I can't reproduce this in the current version. It may have been fixed by the recent Rails 6.1 upgrade. Can you re-test? If there's still an issue, can you confirm the configuration of the webhook?

**Comment by belghitioth** [comment] 2023-04-12 09:53
Hello, I created the issue when it occurs after the new release of postal 2.1.3 two weeks ago
Then it has been rollbacked to version 2.1.2 and it was ok.
Didn't try yet with the latest new release 2.1.3 :) I will let you know

**Comment by adamcooke** [comment] 2024-01-30 11:07
Can't reproduce this

**Closed by adamcooke** 2024-01-30 11:07 UTC
Labels: bug
