### ISSUE TITLE
Encoding display is incorrect in the web interface Postal

### ISSUE THREAD

**Issue by andrsharov** [postalserver/postal#2698] opened 2023-11-14 18:59 UTC
Hi, there.

After upgrade to version 2.1.4 I've catch some problems with web interface Postal.
The links "Plain text" and "HTML"
/org/dg/servers/dg/messages/609085/plain 
/org/dg/servers/dg/messages/609085/html

Cyrillic symbols shows as "questions signs" like this �������� 

But at destination email boxes all shows correct: And at the email clients like Thunderd, and at the web interfaces like Gmail.

Can you advice to me, how to trouble the situation?

![image](https://github.com/postalserver/postal/assets/44819772/76084aa7-f44d-49a6-b45f-38620a847618)

**Comment by willpower232** [comment] 2023-11-15 11:09
is this a duplicate of #2494 ?

**Comment by andrsharov** [comment] 2023-11-15 11:24
@willpower232 , yes  

I caught this error after update 2.1.2 ->  2.1.4

**Comment by Toni202012569** [comment] 2023-11-29 13:37
Where is the solution to this problem?

**Comment by adamcooke** [comment] 2024-02-01 13:46
Duplicate of #2494

**Closed** 2024-02-01 13:46 UTC
Labels: bug

**Comment by andrsharov** [comment] 2024-02-12 09:07
After the update the bug was fixed . Thanks!
