### ISSUE TITLE
Issue with attachment in Email API 

### ISSUE THREAD

**Issue by rccess** [postalserver/postal#2377] opened 2023-03-16 09:30 UTC
i am trying to send emails with attachment from email API 

attachment picked successfully but file got courrepted

i have tested with word, pdf , txt file. all are receiving as a corrupted files,

here is the code i am using
for txt
----------------------------------------
{
"to": ["[abc@gmail.com](mailto:abc@gmail.com)"
],
"from":"company[info@xyz.com](mailto:info@xyz.com)",
"sender": "company",
"subject": "Email API Test",
"plain_body": "hello this email api checking",
"attachments": [{
"name": "docs.txt",
"content_type": "text/plain",
"data": "base64_encode($data)",
"content_url": "https://www.xyz.com/wp-content/uploads/2023/03/docs.txt"
}]
}

for docx
{
"to": ["[abc@gmail.com](mailto:abc@gmail.com)"
],
"from":"company[info@xyz.com](mailto:info@xyz.com)",
"sender": "company",
"subject": "Email API Test",
"plain_body": "hello this email api checking",
"attachments": [{
"name": "123.docx",
"content_type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
"data": "base64_encode($data)",
"content_url": "http://domain.com/images/article/123.docx"
}]
}

is there anything which i am missing  ?

**Comment by willpower232** [comment] 2023-03-16 15:43
duplicate of #2375

**Closed by willpower232** 2023-03-16 15:43 UTC
