### ISSUE TITLE
Internal error occurred when adding email addresses to suppression list

### ISSUE THREAD

**Issue by pplulee** [postalserver/postal#2435] opened 2023-04-29 10:02 UTC
## Describe the bug

When the number of delivery attempts exceeds the pre-set value, the email addresses should be added to the suppression list. But this operation failed due to an internal error `FrozenError: can't modify frozen String: ""` , and the queue keeps retrying to send that mail after some time.

I had this problem on at least two machines

This problem only occurs in the latest version (2.1.4), I fell back to 2.1.2 without encountering the problem.

## To Reproduce

Let an email fail to be sent, and when the number of attempts exceeds the preset value, the mailbox is not blacklisted, but an internal error is obtained.

## Screenshots

Here, the maximum attempt at this time is 1
![20230429105412](https://user-images.githubusercontent.com/46434255/235296646-3626e4a4-774c-4965-b6b3-4be090914159.png)

## Environment details 

 - OS: Ubuntu20 and Debian10
 - Postal Version: 2.1.4
 - MariaDB Version: 10.7.3 and 10.11.2

## Additional information/context

Here is the sample of error information

[9] [2023-04-29T05:19:58.044] INFO -- : [YMUXGKRN9Z] Started processing UnqueueMessageJob job
[9] [2023-04-29T05:19:58.050] INFO -- : [YMUXGKRN9Z] Lock acquired for queued message 3912
[9] [2023-04-29T05:19:58.056] INFO -- : [YMUXGKRN9Z] Found 0 associated messages to process at the same time (batch key: outgoing-aliyun.com)
[9] [2023-04-29T05:19:58.057] INFO -- : [YMUXGKRN9Z] [2::3891 3912] Got queued message with exclusive lock
[9] [2023-04-29T05:19:58.059] INFO -- : [YMUXGKRN9Z] Added xxx@aliyun.com to suppression list because maximum attempts has been reached
[9] [2023-04-29T05:19:58.069] INFO -- : [YMUXGKRN9Z] [2::3891 3912] Internal error: FrozenError: can't modify frozen String: ""
[9] [2023-04-29T05:19:58.069] INFO -- : [YMUXGKRN9Z] [2::3891 3912] /opt/postal/app/lib/postal/message_db/delivery.rb:51:in 'force_encoding'
[9] [2023-04-29T05:19:58.069] INFO -- : [YMUXGKRN9Z] [2::3891 3912] /opt/postal/app/lib/postal/message_db/delivery.rb:51:in 'webhook_hash'
[9] [2023-04-29T05:19:58.069] INFO -- : [YMUXGKRN9Z] [2::3891 3912] /opt/postal/app/lib/postal/message_db/delivery.rb:43:in 'send_webhooks'
[9] [2023-04-29T05:19:58.069] INFO -- : [YMUXGKRN9Z] [2::3891 3912] /opt/postal/app/lib/postal/message_db/delivery.rb:11:in 'create'
[9] [2023-04-29T05:19:58.069] INFO -- : [YMUXGKRN9Z] [2::3891 3912] /opt/postal/app/lib/postal/message_db/message.rb:124:in 'create_delivery'
[9] [2023-04-29T05:19:58.069] INFO -- : [YMUXGKRN9Z] [2::3891 3912] /opt/postal/app/app/jobs/unqueue_message_job.rb:69:in 'block in perform'
[9] [2023-04-29T05:19:58.069] INFO -- : [YMUXGKRN9Z] [2::3891 3912] /opt/postal/app/app/jobs/unqueue_message_job.rb:31:in 'each'
[9] [2023-04-29T05:19:58.069] INFO -- : [YMUXGKRN9Z] [2::3891 3912] /opt/postal/app/app/jobs/unqueue_message_job.rb:31:in 'perform'
[9] [2023-04-29T05:19:58.069] INFO -- : [YMUXGKRN9Z] [2::3891 3912] /opt/postal/app/lib/postal/worker.rb:64:in 'receive_job'
[9] [2023-04-29T05:19:58.069] INFO -- : [YMUXGKRN9Z] [2::3891 3912] /opt/postal/app/lib/postal/worker.rb:96:in 'block in join_queue'
[9] [2023-04-29T05:19:58.069] INFO -- : [YMUXGKRN9Z] [2::3891 3912] /usr/local/bundle/gems/bunny-2.20.3/lib/bunny/consumer.rb:56:in 'call'
[9] [2023-04-29T05:19:58.069] INFO -- : [YMUXGKRN9Z] [2::3891 3912] /usr/local/bundle/gems/bunny-2.20.3/lib/bunny/channel.rb:1842:in 'block in handle_frameset'
[9] [2023-04-29T05:19:58.069] INFO -- : [YMUXGKRN9Z] [2::3891 3912] /usr/local/bundle/gems/bunny-2.20.3/lib/bunny/consumer_work_pool.rb:108:in 'block (2 levels) in run_loop'
[9] [2023-04-29T05:19:58.069] INFO -- : [YMUXGKRN9Z] [2::3891 3912] /usr/local/bundle/gems/bunny-2.20.3/lib/bunny/consumer_work_pool.rb:103:in 'loop'
[9] [2023-04-29T05:19:58.069] INFO -- : [YMUXGKRN9Z] [2::3891 3912] /usr/local/bundle/gems/bunny-2.20.3/lib/bunny/consumer_work_pool.rb:103:in 'block in run_loop'
[9] [2023-04-29T05:19:58.069] INFO -- : [YMUXGKRN9Z] [2::3891 3912] /usr/local/bundle/gems/bunny-2.20.3/lib/bunny/consumer_work_pool.rb:102:in 'catch'
[9] [2023-04-29T05:19:58.069] INFO -- : [YMUXGKRN9Z] [2::3891 3912] /usr/local/bundle/gems/bunny-2.20.3/lib/bunny/consumer_work_pool.rb:102:in 'run_loop'
[9] [2023-04-29T05:19:58.071] INFO -- : [YMUXGKRN9Z] [2::3891 3912] Queued message was unlocked
[9] [2023-04-29T05:19:58.114] INFO -- : [YMUXGKRN9Z] Finished processing UnqueueMessageJob job in 0.070203205s

**Comment by willpower232** [comment] 2023-04-29 17:55
duplicate of #2153

**Closed by willpower232** 2023-04-29 17:55 UTC
Labels: bug
