### ISSUE TITLE
Postal gives a random 403 after many UI requests

### ISSUE THREAD

**Issue by christiaangoossens** [postalserver/postal#2804] opened 2024-02-14 12:32 UTC
## Describe the bug

After a succesful configuration and many UI requests, a random 403 is triggered. This causes:

- Requests to no longer show up on the web container log
- 403 status code to be sent back from the web container on any subsequent request

It disappears when you remove the postal session cookie.

## To Reproduce

1. Fully setup postal as described on the site
2. Use nginx as your ingress (but this should also happen for caddy)
3. Use the UI for a while, until you get a 403

## Expected behaviour

No 403 should be triggered.

## Screenshots

Irrelevant

## Environment details 

Run within Docker with Nginx as an ingress.

## Additional information/context

Already tested and not the problem:

- The ingress itself functions correctly
- The requests are actually sent to the container, but no logs are created
- Resetting other cookies has no effect, only postal session.

**Comment by christiaangoossens** [comment] 2024-02-14 12:33
Possibly related to:

https://github.com/postalserver/postal/issues/2459
https://github.com/postalserver/postal/issues/487

Note that generally, you just get the normal UI, until after about 30-50 requests you suddenly start getting 403's.

**Comment by adamcooke** [comment] 2024-04-20 09:46
Sadly, I can't reproduce this and nobody has been able to provide any logs when it happens. In light of that, I'm closing this issue until such data can be provided.

**Closed by adamcooke** 2024-04-20 09:46 UTC
Labels: bug
