### ISSUE TITLE
Make user command failing with wrong number of arguments error

### ISSUE THREAD

**Issue by ankitjaggi** [postalserver/postal#2508] opened 2023-06-20 15:00 UTC
I am trying to setup Postal v2.1.4 (latest version) on an Amazon Linux 2 machine. Everything is working except creation of a master user. Every time I try to run `postal make-user` I get the following error.

```
/usr/local/bundle/gems/i18n-1.12.0/lib/i18n.rb:210:in `translate': wrong number of arguments (given 2, expected 0..1) (ArgumentError)
	from /usr/local/bundle/gems/dynamic_form-1.1.4/lib/active_model/dynamic_errors.rb:35:in `block (2 levels) in full_messages'
	from /usr/local/bundle/gems/dynamic_form-1.1.4/lib/active_model/dynamic_errors.rb:27:in `each'
	from /usr/local/bundle/gems/dynamic_form-1.1.4/lib/active_model/dynamic_errors.rb:27:in `block in full_messages'
	from /usr/local/bundle/gems/activemodel-6.1.7.3/lib/active_model/errors.rb:256:in `block in each'
	from /usr/local/bundle/gems/activemodel-6.1.7.3/lib/active_model/errors.rb:256:in `each'
	from /usr/local/bundle/gems/activemodel-6.1.7.3/lib/active_model/errors.rb:256:in `each'
	from /usr/local/bundle/gems/dynamic_form-1.1.4/lib/active_model/dynamic_errors.rb:16:in `full_messages'
	from /opt/postal/app/lib/postal/user_creator.rb:26:in `start'
	from script/make_user.rb:10:in `<main>'
```

_Originally posted by @ankitjaggi in https://github.com/postalserver/postal/discussions/2502_

**Comment by arnaullopxirau** [comment] 2023-08-01 09:13
Same problem here. Any workaround? 
We tried with different versions of Ubuntu. Is there any recommended linux distribution?

**Comment by NeilTorrero** [comment] 2023-08-01 10:34
To be able to use the make-user as a temporal fix you can modify the Docker Compose File (`/opt/postal/install/docker_compose.yml`) before the `postal initialize` step. 
And change the version of the images from v2.1.4 to v2.1.2, where said command still works.

After the set up you can upgrade the version if you no longer need the command.

**Comment by arnaullopxirau** [comment] 2023-08-01 10:42
It worked! Thanks a lot!

**Comment by arthurzenika** [comment] 2023-11-03 15:30
Got this error too.

**Comment by hiralalmahival007** [comment] 2023-11-24 12:04
It worked! Thanks a lot!

**Comment by szc3h9** [comment] 2024-01-01 08:00
> To be able to use the make-user as a temporal fix you can modify the Docker Compose File (`/opt/postal/install/docker_compose.yml`) before the `postal initialize` step. And change the version of the images from v2.1.4 to v2.1.2, where said command still works.
> 
> After the setup you can upgrade the version if you no longer need the command.

it doesn‘t seem to work. please look this: 
[root@localhost podman]# postal initialize
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 3.4.4
podman pull ghcr.io/postalserver/postal:2.1.2
Trying to pull ghcr.io/postalserver/postal:2.1.2...
Getting image source signatures
Copying blob 5fdd409f4b2b skipped: already exists  
Copying blob 85bed84afb9a skipped: already exists  
Copying blob 459c58f08462 skipped: already exists  
Copying blob 4ee16f45eff9 skipped: already exists  
Copying blob 1e64582c7ca0 skipped: already exists  
Copying blob 5d3b29586333 skipped: already exists  
Copying blob 2cee68386155 skipped: already exists  
Copying blob 3e959058363d skipped: already exists  
Copying blob 023def73b4ba skipped: already exists  
Copying blob 9f833da6d589 skipped: already exists  
Copying blob 16e14e2f8081 skipped: already exists  
Copying blob fa3069e6cecf skipped: already exists  
Copying blob 4f4fb700ef54 skipped: already exists  
Copying blob 822f5cae803f skipped: already exists  
Copying blob 32e3346827f9 skipped: already exists  
Copying blob c300db466752 skipped: already exists  
Copying blob 2831bfa0be44 skipped: already exists  
Copying blob 00923dca4adc skipped: already exists  
Copying blob 7b073faa90ff skipped: already exists  
Copying blob 52727a4f11f3 skipped: already exists  
Copying blob 53600d146804 skipped: already exists  
Copying blob 86e550eeb330 skipped: already exists  
Copying config 1edd9fbaef done  
Writing manifest to image destination
Storing signatures
1edd9fbaef6bde867e5f1ea1c2f5d43a7516178d391fb597181da59c1a01afcb
exit code: 0
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 3.4.4
podman run --name=postal_runner_tmp5995 -i --label io.podman.compose.config-hash=a9a46dc6710641d3ba6b0acc46808a3cb9f94bc56c5df49342cfca6f42201a94 --label io.podman.compose.project=postal --label io.podman.compose.version=1.0.6 --label PODMAN_SYSTEMD_UNIT=podman-compose@postal.service --label com.docker.compose.project=postal --label com.docker.compose.project.working_dir=/opt/postal/install --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=runner -v /opt/postal/config:/config --network host --tty ghcr.io/postalserver/postal:2.1.2 postal initialize
Initializing database
RSA Encryption not supported - caching_sha2_password plugin was built with GnuTLS support
Couldn't create 'postal' database. Please check your configuration.
rake aborted!
Mysql2::Error: RSA Encryption not supported - caching_sha2_password plugin was built with GnuTLS support
/usr/local/bundle/gems/mysql2-0.5.3/lib/mysql2/client.rb:90:in `connect'
/usr/local/bundle/gems/mysql2-0.5.3/lib/mysql2/client.rb:90:in `initialize'
/usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/connection_adapters/mysql2_adapter.rb:22:in `new'
/usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/connection_adapters/mysql2_adapter.rb:22:in `mysql2_connection'
/usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:830:in `new_connection'
/usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:874:in `checkout_new_connection'
/usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `try_to_checkout_new_connection'
/usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:814:in `acquire_connection'
/usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:538:in `checkout'
/usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
/usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:1033:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/connection_handling.rb:90:in `connection'
/usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/tasks/mysql_database_tasks.rb:6:in `connection'
/usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/tasks/mysql_database_tasks.rb:14:in `create'
/usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/tasks/database_tasks.rb:119:in `create'
/usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/tasks/database_tasks.rb:139:in `block in create_current'
/usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/tasks/database_tasks.rb:316:in `block in each_current_configuration'
/usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/tasks/database_tasks.rb:313:in `each'
/usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/tasks/database_tasks.rb:313:in `each_current_configuration'
/usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/tasks/database_tasks.rb:138:in `create_current'
/usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/railties/databases.rake:29:in `block (2 levels) in <top (required)>'
/opt/postal/app/bin/bundle:3:in `load'
/opt/postal/app/bin/bundle:3:in `<main>'
Tasks: TOP => db:create
(See full trace by running task with --trace)
exit code: 1
[root@localhost podman]# ls
run-postal-mysql.sh  run-postal-rabbitmq.sh
[root@localhost podman]# postal make-user
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 3.4.4
podman run --name=postal_runner_tmp14067 -i --label io.podman.compose.config-hash=a9a46dc6710641d3ba6b0acc46808a3cb9f94bc56c5df49342cfca6f42201a94 --label io.podman.compose.project=postal --label io.podman.compose.version=1.0.6 --label PODMAN_SYSTEMD_UNIT=podman-compose@postal.service --label com.docker.compose.project=postal --label com.docker.compose.project.working_dir=/opt/postal/install --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=runner -v /opt/postal/config:/config --network host --tty ghcr.io/postalserver/postal:2.1.2 postal make-user
Postal User Creator
Enter the information required to create a new Postal user.
This tool is usually only used to create your initial admin user.

/usr/local/bundle/gems/mysql2-0.5.3/lib/mysql2/client.rb:90:in `connect': RSA Encryption not supported - caching_sha2_password plugin was built with GnuTLS support (Mysql2::Error)
        from /usr/local/bundle/gems/mysql2-0.5.3/lib/mysql2/client.rb:90:in `initialize'
        from /usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/connection_adapters/mysql2_adapter.rb:22:in `new'
        from /usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/connection_adapters/mysql2_adapter.rb:22:in `mysql2_connection'
        from /usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:830:in `new_connection'
        from /usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:874:in `checkout_new_connection'
        from /usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `try_to_checkout_new_connection'
        from /usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:814:in `acquire_connection'
        from /usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:538:in `checkout'
        from /usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
        from /usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:1033:in `retrieve_connection'
        from /usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
        from /usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/connection_handling.rb:90:in `connection'
        from /usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/model_schema.rb:466:in `load_schema!'
        from /usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/attributes.rb:234:in `load_schema!'
        from /usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/attribute_decorators.rb:51:in `load_schema!'
        from /usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/model_schema.rb:459:in `block in load_schema'
        from /usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
        from /usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/model_schema.rb:456:in `load_schema'
        from /usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/model_schema.rb:346:in `attribute_types'
        from /usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/attribute_methods.rb:230:in `has_attribute?'
        from /usr/local/bundle/gems/activerecord-5.2.6.2/lib/active_record/inheritance.rb:55:in `new'
        from /opt/postal/app/lib/postal/user_creator.rb:12:in `start'
        from script/make_user.rb:7:in `<main>'
exit code: 1

**Comment by willpower232** [comment] 2024-01-03 09:13
> RSA Encryption not supported - caching_sha2_password plugin was built with GnuTLS support

It looks like your database is set up slightly weirdly, not sure how you've achieved that though.

**Comment by BobTB** [comment] 2024-01-16 10:50
So this is still broken? Can not be installed by default settings on ubuntu? Works with some other distribution?

**Comment by szc3h9** [comment] 2024-01-16 11:29
Sorry, I forgot to synchronize my latest progress. I did not attempt to run it on Ubuntu, but instead chose Rocky Linux 9 and replace mysql docker with mariadb docker. (successful).

**Comment by BobTB** [comment] 2024-01-16 12:34
ok. Will use 2.1.2 then, as it seems to work, why 2.1.4 is not getting fixed is beyond me.

**Comment by adamcooke** [comment] 2024-02-07 10:21
This should be fixed. I cannot reproduce in 2.2.2.

**Closed** 2024-02-21 23:59 UTC
Labels: bug
