### ISSUE TITLE
FrozenError: can't modify frozen String: ""

### ISSUE THREAD

**Issue by gigbuilder** [postalserver/postal#2707] opened 2023-11-24 16:26 UTC
This began a few months ago where random addresses would fail to send, with ERROR - FrozenError: can't modify frozen String: "" and then adding the email to the suppression list.
I deleted the entire server, fired up a new CentOS 7 fresh install - completely rebuilt Postal, and things worked for a few days, but the error has returned and seems to attack more email addresses each day.
I have no idea what is causing the problem.  Postal has worked great for us since 2020.

**Comment by brywhi** [comment] 2023-11-29 03:53
I have the same issue. Still fighting it

**Comment by brywhi** [comment] 2023-11-29 05:44
@gigbuilder  - found that this worked for me: 
https://github.com/postalserver/postal/issues/2153#issuecomment-1725237569

**Comment by pdifeo** [comment] 2023-12-16 19:55
Is there a reason why this small modification is not released? In any case, the error is in the worker-1 container. I then ran

`postal bash worker`

I edited the file 

`lib/postal/message_db/delivery.rb`

file by making the change

`output: output.to_s.dup.force_encoding("UTF-8").scrub.truncate(512)`

but the problem is still there. I think the worker needs to restart to pick up the change. Can anyone tell me how to do this?

Thanks in advance

**Comment by evdbovenkamp** [comment] 2023-12-17 09:50
Same issue here...

**Comment by pdifeo** [comment] 2023-12-22 14:47
> Is there a reason why this small modification is not released? In any case, the error is in the worker-1 container. I then ran
> 
> `postal bash worker`
> 
> I edited the file
> 
> `lib/postal/message_db/delivery.rb`
> 
> file by making the change
> 
> `output: output.to_s.dup.force_encoding("UTF-8").scrub.truncate(512)`
> 
> but the problem is still there. I think the worker needs to restart to pick up the change. Can anyone tell me how to do this?
> 
> Thanks in advance

bump!

**Comment by pdifeodfware** [comment] 2024-01-06 13:14
To make the change operational, perform
`docker restart postal-worker`

**Comment by seebeen** [comment] 2024-01-16 13:42
@3willpower23 @adamcooke - Is this project still maintained?
If not. Can you reassign to another maintainer?

**Comment by adamcooke** [comment] 2024-02-01 13:46
This should already have been fixed in 2.1.6.

**Closed by adamcooke** 2024-02-01 13:46 UTC
Labels: bug
